const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAIL = 'GET_FAIL';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS';
const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
const CREATE_REQUEST = 'CREATE_REQUEST';
const CREATE_SUCCEEDED = 'CREATE_SUCCEEDED';
const CREATE_FAILED = 'CREATE_FAILED';
const CLEAR_CART = 'CLEAR_CART';

export {
  GET_SUCCESS,
  GET_FAIL,
  GET_REQUEST,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  USER_SIGNIN,
  USER_SIGNOUT,
  SAVE_SHIPPING_ADDRESS,
  SAVE_PAYMENT_METHOD,
  CREATE_REQUEST,
  CREATE_SUCCEEDED,
  CREATE_FAILED,
  CLEAR_CART,
};
